---
- name: Install awscli and python libs
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - awscli
    - python2-botocore
    - python2-boto3
    - python3-botocore
    - python3-boto3
  tags: aws awscli
