---
- name: Install npm packages
  npm:
    name: "{{ item }}"
    state: present
    global: true
  with_items:
    - lighthouse
    - grunt-cli
    - gulp-cli
    - "@vue/cli"
    - yarn
    - stylelint
  tags: npm
